### ISSUE TITLE
Incorrect workload values in Topology Dashboard's workload combo box

### ISSUE THREAD

**Issue by J-lena** [KindlingProject/kindling#141]
**Describe the bug**
The option in the workload combo box  is not incomplete

**What did you expect to see?**
There are four options:  bookdemo 、bookdemo2 、bookdemo3 and jmeterv2 

**What did you see instead?**
There are only there options: bookdemo 、bookdemo2 and bookdemo3 

**Screenshots**
![image](https://user-images.githubusercontent.com/97420104/159837619-0b7916fc-bdcc-40a2-95cd-2bc1458f0278.png)

In my Kubernetes, the resources are:
![image](https://user-images.githubusercontent.com/97420104/159837746-dddb9e8b-50d4-41d8-8bdf-46eaff862387.png)

**Comment by dxsup** [comment]
This issue has been fixed.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/46807570/204721118-6485074f-715c-411c-b500-a3dfd33ce99f.png">
