### ISSUE TITLE
Support IO latency analysis  in  the request tracing analysis process

### ISSUE THREAD

**Issue by J-lena** [KindlingProject/kindling#176]
Currently, we break the request latency into 3 parts that don't include I/O latency, so we can't get the influence of the IO part. The feature can indicate if I/O high latency affects the request latency.

![image](https://user-images.githubusercontent.com/97420104/163507416-6ce40ce6-88d2-47ee-9432-b7b0064da995.png)

**Comment by dxsup** [comment]
Implementing this metric won't be scheduled on our calendar recently. Maybe we can add it later. If there is anyone who needs it, please feel free to open this issue again.
