### ISSUE TITLE
An unexpected topology is recorded when src_workload is using hostNetWork

### ISSUE THREAD

**Issue by NeJan2020** [KindlingProject/kindling#187]
**Describe the bug**
After enabling the configuration `store_external_src_ip: true`, we expect to see the access topology from outside the cluster. However, we found a topology with external access to services that are only used inside the cluster.  

**How to reproduce?**
1. Use calico as your cluster network plugin in 'IPIP' mode
2. Set any workload's (A) network policy to HostNetWork.
3. Use this workload to call another workload (B) in your cluster
4. You will find that this call generates two topologies, one for A to call B, and the other for the IP of tunl0 of the node where A is located as the source IP to call B.

**What did you expect to see?**
Only the A -> B should be recorded.

**Screenshots**
<img width="666" alt="image" src="https://user-images.githubusercontent.com/64676199/164194521-850ab120-1bcf-49b7-8a69-3b14ae052e96.png">

**What config did you use?**
store_external_src_ip: true

**Additional context**
The most common scenario that causes this problem is to expose the services in the cluster through the four-layer load mode of Nginx-Ingress.

**Comment by YDMsama** [comment]
Hi @NeJan2020,

Thanks for the detailed issue. Based on our analysis:

External Topology:
When store_external_src_ip is true, the code checks for ExternalClusterNamespace and generates an external topology, likely the expected A -> B.

Additional Topology:
Another topology is always generated, potentially the unexpected one with the tunl0 IP.

Potential Cause:
The function dealWithPreAggMetricGroups in net_adapter.go consistently generates the additional topology. While the external topology is conditionally generated, the additional one isn't. The createNetMetricResults function further refines the data group to produce metrics for these topologies.

Potential Solution:
To achieve the desired A -> B topology, we could add a condition to the always-generated topology. Specifically, when store_external_src_ip is set to true, we can skip generating the second topology. This would prevent the creation of the unexpected topology and align with your expectations.

We'll continue our investigation. Any further insights from your side would be valuable.

Best,
YDMsama
