### ISSUE TITLE
Is zero srtt correct? 

### ISSUE THREAD

**Issue by J-lena** [KindlingProject/kindling#248]
**Describe the bug**
In topology dashboard some connections show zero srtt , this does't look right. 

**How to reproduce?**
Access the demo website, http://218.75.39.90:30010/grafana/d/MiIYJE57k/kindling-topology?orgId=1
Select the srtt metric ,you rill see the zero srtt .
![image](https://user-images.githubusercontent.com/97420104/173485797-b199f466-19b9-424d-998b-5d2737371333.png)

**What did you expect to see?**
A specific value of srtt

**What did you see instead?**
Zero value displayed

**Additional context**
Prometheus also lack of the srtt metric  between ingress-nginx and cloudmonitor namespace for example
![image](https://user-images.githubusercontent.com/97420104/173487661-95882edf-1509-43a5-aac5-14daa453cc45.png)

**Comment by dxsup** [comment]
I figured this is related to #444. Now, this issue is fixed.

**Comment by dxsup** [comment]
I figured this is related to #444. Now, this issue is fixed.
