### ISSUE TITLE
Some dns request doesn't have any request_content

### ISSUE THREAD

**Issue by NeJan2020** [KindlingProject/kindling#262]
**Describe the bug**

I have received some DNS trace in Prometheus that doesn't have any request_content, and I cannot find out why.

**How to reproduce?**

Using the PQL below to search in the Demo

```
kindling_trace_request_duration_nanoseconds{is_server="true", protocol="dns",request_content=""}
```

**What did you expect to see?**

Normal Request with a request_content
<img width="408" alt="image" src="https://user-images.githubusercontent.com/64676199/174923048-bb15530b-0c48-4f11-8289-128ae1ba2a81.png">

**What did you see instead?**
Abnormal Request

<img width="325" alt="image" src="https://user-images.githubusercontent.com/64676199/174922696-59c98743-a305-4601-9a71-22da1e8d983a.png">

**Additional context**

I guess that may be a no-response request or the DNS protocol parser meets some problems.

**Comment by dxsup** [comment]
We have addressed the issue where DNS transport over TCP was not supported. In this scenario, a two-octet length field is present at the start of the message header. The fix for this issue can be found in PR #524.
