### ISSUE TITLE
CgoReceiver 调动   C.getKindlingEvent 出错

### ISSUE THREAD

**Issue by winston-xing** [KindlingProject/kindling#288]
我是使用deepin20.6,运行  kindling-0.3.0，出现下面的错误
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fc85d24f867]

runtime stack:
runtime.throw(0x1c4738c, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 28 [syscall]:
runtime.cgocall(0x17c1f30, 0xc00005f758, 0xc000010008)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00005f728 sp=0xc00005f6f0 pc=0x406ebb
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver._Cfunc_getKindlingEvent(0xc000010008, 0xc000000000)
        _cgo_gotypes.go:152 +0x45 fp=0xc00005f758 sp=0xc00005f728 pc=0x17bd745
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent.func1(0xc000010008, 0xc0005403c0)
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x5d fp=0xc00005f788 sp=0xc00005f758 pc=0x17bf3dd
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent(0xc0001006e0)
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x94 fp=0xc00005f7d8 sp=0xc00005f788 pc=0x17bdd94
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00005f7e0 sp=0xc00005f7d8 pc=0x471561
created by github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).Start
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:66 +0xd6

**Comment by dxsup** [comment]
请问是怎么运行出现的这个问题？是在本地编译后直接启动的吗？麻烦描述一下如何复现。

**Comment by winston-xing** [comment]
我使用的操作系统 是 deepin20.6，内核：5.10.83-amd64-desktop
llvm和clang版本：13.0.1
gcc版本： 10.2.0 

正常编译生成：
libkindling.so
5.10.83-amd64-desktop.ko
5.10.83-amd64-desktop.o
kindling-collector

我本地没有安装k8s,只想使用bpf获取一下http和mysql的内核数据；
所以，我把application.go中关于k8s的Processor的代码注释了；
<img width="960" alt="info" src="https://user-images.githubusercontent.com/37855334/177704959-9bde920a-e008-4741-923a-94db8db5809f.png">
<img width="960" alt="info1" src="https://user-images.githubusercontent.com/37855334/177704968-f08be653-33d9-4c42-9796-f9822ae84a8e.png">

执行 sh start.sh 后出现：
regs=2 stack=0 before 1: (b7) r1 = 0
3: (bf) r2 = r10
4: (07) r2 += -16
5: (18) r1 = 0xffff8b2b90395400
7: (85sub event name:syscall_exit-writev  &&  category:net
sub event name:syscall_exit-readv  &&  category:net
sub event name:syscall_exit-write  &&  category:net
sub event name:syscall_exit-read  &&  category:net
sub event name:syscall_exit-sendto  &&  category:net
sub event name:syscall_exit-recvfrom  &&  category:net
sub event name:syscall_exit-sendmsg  &&  category:net
sub event name:syscall_exit-recvmsg  &&  category:net
sub event name:kprobe-tcp_close  &&  category:
sub event name:kprobe-tcp_rcv_established  &&  category:
sub event name:kprobe-tcp_drop  &&  category:
sub event name:kprobe-tcp_retransmit_skb  &&  category:
sub event name:syscall_exit-connect  &&  category:
sub event name:kretprobe-tcp_connect  &&  category:
sub event name:kprobe-tcp_set_state  &&  category:
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fc85d24f867]

runtime stack:
runtime.throw(0x1c4738c, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 28 [syscall]:
runtime.cgocall(0x17c1f30, 0xc00005f758, 0xc000010008)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00005f728 sp=0xc00005f6f0 pc=0x406ebb
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver._Cfunc_getKindlingEvent(0xc000010008, 0xc000000000)
        _cgo_gotypes.go:152 +0x45 fp=0xc00005f758 sp=0xc00005f728 pc=0x17bd745
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent.func1(0xc000010008, 0xc0005403c0)
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x5d fp=0xc00005f788 sp=0xc00005f758 pc=0x17bf3dd
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent(0xc0001006e0)
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x94 fp=0xc00005f7d8 sp=0xc00005f788 pc=0x17bdd94
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00005f7e0 sp=0xc00005f7d8 pc=0x471561
created by github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).Start
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:66 +0xd6

**Comment by jundizhou** [comment]
这看起来像是ebpf模块报的错误，你可以使用以下命令获取更多错误信息：
strace -febpf  ./collector -config=xxxxx

**Comment by winston-xing** [comment]
加了strace -febpf ./collector -config=xxxxx 后的异常日志：
sub event name:kprobe-tcp_set_state  &&  category:
[pid 14623] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f07d784c867]

runtime stack:
runtime.throw(0x1c4738c, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 24 [syscall]:
runtime.cgocall(0x17c1f30, 0xc0002cb758, 0xc000010008)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0002cb728 sp=0xc0002cb6f0 pc=0x406ebb
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver._Cfunc_getKindlingEvent(0xc000010008, 0xc000000000)
        _cgo_gotypes.go:152 +0x45 fp=0xc0002cb758 sp=0xc0002cb728 pc=0x17bd745
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent.func1(0xc000010008, 0xc000261da0)
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x5d fp=0xc0002cb788 sp=0xc0002cb758 pc=0x17bf3dd
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent(0xc0003a6000)
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x94 fp=0xc0002cb7d8 sp=0xc0002cb788 pc=0x17bdd94
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0002cb7e0 sp=0xc0002cb7d8 pc=0x471561
created by github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).Start
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:66 +0xd6

goroutine 1 [runnable]:
os/signal.signal_enable(0x2ef770a600000002)
        /usr/local/go/src/runtime/sigqueue.go:246 +0x72
os/signal.enableSignal(...)
        /usr/local/go/src/os/signal/signal_unix.go:49
os/signal.Notify.func1(0x2)
        /usr/local/go/src/os/signal/signal.go:145 +0x88
os/signal.Notify(0xc0002600c0, 0xc0001a7f58, 0x2, 0x2)
        /usr/local/go/src/os/signal/signal.go:165 +0x185
main.main()
        /data/software/kindling-0.3.0/collector/cmd/kindling-collector/main.go:29 +0x1fa

goroutine 7 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a4e220)
        /home/huabin/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
        /home/huabin/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdf

goroutine 8 [chan receive]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc0001d1ec0)
        /home/huabin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x5d
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
        /home/huabin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0x75

goroutine 9 [select]:
go.opentelemetry.io/otel/sdk/metric/controller/basic.(*Controller).runTicker(0xc00013f220, 0x1e75aa8, 0xc000132010, 0xc000100de0)
        /home/huabin/go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v0.25.0/controller/basic/controller.go:226 +0xcb
created by go.opentelemetry.io/otel/sdk/metric/controller/basic.(*Controller).Start
        /home/huabin/go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v0.25.0/controller/basic/controller.go:191 +0x135

goroutine 16 [chan receive]:
github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).consumerFdNoReusingTrace(0xc000159a20)
        /data/software/kindling-0.3.0/collector/pkg/component/analyzer/network/network_analyzer.go:189 +0x49
created by github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).Start
        /data/software/kindling-0.3.0/collector/pkg/component/analyzer/network/network_analyzer.go:93 +0x85

goroutine 11 [select]:
github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.NewCircuitBreaker.func1(0xc00023ec00)
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/circuit_breaker.go:70 +0xe9
created by github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.NewCircuitBreaker
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/circuit_breaker.go:67 +0xb5

goroutine 14 [IO wait]:
internal/poll.runtime_pollWait(0x7f07ae4c3eb8, 0x72, 0xc0002a9f48)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000261bd8, 0x72, 0x1, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).RawRead(0xc000261bc0, 0xc0003f85a0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:553 +0xff
os.(*rawConn).Read(0xc0000119b8, 0xc0003f85a0, 0x45264c, 0x28)
        /usr/local/go/src/os/rawconn.go:31 +0x65
github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Socket).recvmsg(0xc00022e900, 0xc000388000, 0x8000, 0x8000, 0xc000284060, 0x28, 0x28, 0x0, 0x0, 0x1000, ...)
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/socket.go:269 +0x12e
github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Socket).ReceiveInto(0xc00022e900, 0xc0002c3000, 0x1000, 0x1000, 0xc000060690, 0x4eccc5, 0xc000261bc0, 0xc0003903c0, 0x0, 0x0)
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/socket.go:123 +0xb4
github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Consumer).receive(0xc00026aa00, 0xc000261c20)
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/consumer.go:407 +0x26f
github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Consumer).Events.func1(0xc000261c20, 0xc00026aa00)
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/consumer.go:158 +0x7e
created by github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Consumer).Events
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/consumer.go:150 +0x10b

goroutine 23 [select]:
github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).consumeEvents(0xc0003a6000)
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:92 +0xbc
created by github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).Start
        /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:65 +0xb4

goroutine 15 [select]:
github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*realConntracker).run.func1(0xc000261c20, 0xc000418930)
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/conntracker.go:262 +0xc5
created by github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*realConntracker).run
        /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/conntracker.go:260 +0x85

goroutine 34 [select]:
github.com/Kindling-project/kindling/collector/pkg/component/analyzer/tcpconnectanalyzer.(*TcpConnectAnalyzer).Start.func1(0xc000097f40)
        /data/software/kindling-0.3.0/collector/pkg/component/analyzer/tcpconnectanalyzer/analyzer.go:70 +0xf4
created by github.com/Kindling-project/kindling/collector/pkg/component/analyzer/tcpconnectanalyzer.(*TcpConnectAnalyzer).Start
        /data/software/kindling-0.3.0/collector/pkg/component/analyzer/tcpconnectanalyzer/analyzer.go:67 +0x3f
[pid 14623] +++ exited with 2 +++
[pid 14626] +++ exited with 2 +++
[pid 14625] +++ exited with 2 +++
[pid 14624] +++ exited with 2 +++
[pid 14622] +++ exited with 2 +++
+++ exited with 2 +++
huabin@huabin-PC:/app$

**Comment by jundizhou** [comment]
> 加了strace -febpf ./collector -config=xxxxx 后的异常日志： sub event name:kprobe-tcp_set_state && category: [pid 14623] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} --- fatal error: unexpected signal during runtime execution [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f07d784c867]
> 
> runtime stack: runtime.throw(0x1c4738c, 0x2a) /usr/local/go/src/runtime/panic.go:1117 +0x72 runtime.sigpanic() /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5
> 
> goroutine 24 [syscall]: runtime.cgocall(0x17c1f30, 0xc0002cb758, 0xc000010008) /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0002cb728 sp=0xc0002cb6f0 pc=0x406ebb github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver._Cfunc_getKindlingEvent(0xc000010008, 0xc000000000) _cgo_gotypes.go:152 +0x45 fp=0xc0002cb758 sp=0xc0002cb728 pc=0x17bd745 github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent.func1(0xc000010008, 0xc000261da0) /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x5d fp=0xc0002cb788 sp=0xc0002cb758 pc=0x17bf3dd github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).startGetEvent(0xc0003a6000) /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:79 +0x94 fp=0xc0002cb7d8 sp=0xc0002cb788 pc=0x17bdd94 runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0002cb7e0 sp=0xc0002cb7d8 pc=0x471561 created by github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).Start /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:66 +0xd6
> 
> goroutine 1 [runnable]: os/signal.signal_enable(0x2ef770a600000002) /usr/local/go/src/runtime/sigqueue.go:246 +0x72 os/signal.enableSignal(...) /usr/local/go/src/os/signal/signal_unix.go:49 os/signal.Notify.func1(0x2) /usr/local/go/src/os/signal/signal.go:145 +0x88 os/signal.Notify(0xc0002600c0, 0xc0001a7f58, 0x2, 0x2) /usr/local/go/src/os/signal/signal.go:165 +0x185 main.main() /data/software/kindling-0.3.0/collector/cmd/kindling-collector/main.go:29 +0x1fa
> 
> goroutine 7 [chan receive]: k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a4e220) /home/huabin/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b created by k8s.io/klog/v2.init.0 /home/huabin/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdf
> 
> goroutine 8 [chan receive]: gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc0001d1ec0) /home/huabin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x5d created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1 /home/huabin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0x75
> 
> goroutine 9 [select]: go.opentelemetry.io/otel/sdk/metric/controller/basic.(*Controller).runTicker(0xc00013f220, 0x1e75aa8, 0xc000132010, 0xc000100de0) /home/huabin/go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v0.25.0/controller/basic/controller.go:226 +0xcb created by go.opentelemetry.io/otel/sdk/metric/controller/basic.(*Controller).Start /home/huabin/go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v0.25.0/controller/basic/controller.go:191 +0x135
> 
> goroutine 16 [chan receive]: github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).consumerFdNoReusingTrace(0xc000159a20) /data/software/kindling-0.3.0/collector/pkg/component/analyzer/network/network_analyzer.go:189 +0x49 created by github.com/Kindling-project/kindling/collector/pkg/component/analyzer/network.(*NetworkAnalyzer).Start /data/software/kindling-0.3.0/collector/pkg/component/analyzer/network/network_analyzer.go:93 +0x85
> 
> goroutine 11 [select]: github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.NewCircuitBreaker.func1(0xc00023ec00) /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/circuit_breaker.go:70 +0xe9 created by github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.NewCircuitBreaker /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/circuit_breaker.go:67 +0xb5
> 
> goroutine 14 [IO wait]: internal/poll.runtime_pollWait(0x7f07ae4c3eb8, 0x72, 0xc0002a9f48) /usr/local/go/src/runtime/netpoll.go:222 +0x55 internal/poll.(*pollDesc).wait(0xc000261bd8, 0x72, 0x1, 0x0, 0x0) /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45 internal/poll.(*pollDesc).waitRead(...) /usr/local/go/src/internal/poll/fd_poll_runtime.go:92 internal/poll.(*FD).RawRead(0xc000261bc0, 0xc0003f85a0, 0x0, 0x0) /usr/local/go/src/internal/poll/fd_unix.go:553 +0xff os.(*rawConn).Read(0xc0000119b8, 0xc0003f85a0, 0x45264c, 0x28) /usr/local/go/src/os/rawconn.go:31 +0x65 github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Socket).recvmsg(0xc00022e900, 0xc000388000, 0x8000, 0x8000, 0xc000284060, 0x28, 0x28, 0x0, 0x0, 0x1000, ...) /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/socket.go:269 +0x12e github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Socket).ReceiveInto(0xc00022e900, 0xc0002c3000, 0x1000, 0x1000, 0xc000060690, 0x4eccc5, 0xc000261bc0, 0xc0003903c0, 0x0, 0x0) /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/socket.go:123 +0xb4 github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Consumer).receive(0xc00026aa00, 0xc000261c20) /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/consumer.go:407 +0x26f github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Consumer).Events.func1(0xc000261c20, 0xc00026aa00) /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/consumer.go:158 +0x7e created by github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*Consumer).Events /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/consumer.go:150 +0x10b
> 
> goroutine 23 [select]: github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).consumeEvents(0xc0003a6000) /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:92 +0xbc created by github.com/Kindling-project/kindling/collector/pkg/component/receiver/cgoreceiver.(*CgoReceiver).Start /data/software/kindling-0.3.0/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go:65 +0xb4
> 
> goroutine 15 [select]: github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*realConntracker).run.func1(0xc000261c20, 0xc000418930) /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/conntracker.go:262 +0xc5 created by github.com/Kindling-project/kindling/collector/pkg/metadata/conntracker/internal.(*realConntracker).run /data/software/kindling-0.3.0/collector/pkg/metadata/conntracker/internal/conntracker.go:260 +0x85
> 
> goroutine 34 [select]: github.com/Kindling-project/kindling/collector/pkg/component/analyzer/tcpconnectanalyzer.(*TcpConnectAnalyzer).Start.func1(0xc000097f40) /data/software/kindling-0.3.0/collector/pkg/component/analyzer/tcpconnectanalyzer/analyzer.go:70 +0xf4 created by github.com/Kindling-project/kindling/collector/pkg/component/analyzer/tcpconnectanalyzer.(*TcpConnectAnalyzer).Start /data/software/kindling-0.3.0/collector/pkg/component/analyzer/tcpconnectanalyzer/analyzer.go:67 +0x3f [pid 14623] +++ exited with 2 +++ [pid 14626] +++ exited with 2 +++ [pid 14625] +++ exited with 2 +++ [pid 14624] +++ exited with 2 +++ [pid 14622] +++ exited with 2 +++ +++ exited with 2 +++ huabin@huabin-PC:/app$

可能需要你提供全量的日志，从头开始

**Comment by winston-xing** [comment]
日志太大了，提交不上去；给给个邮箱吗？

**Comment by winston-xing** [comment]
[info.zip](https://github.com/CloudDectective-Harmonycloud/kindling/files/9068101/info.zip)

**Comment by winston-xing** [comment]
全量的日志压缩到info.zip中了。

**Comment by jundizhou** [comment]
regs=8 stack=0 before 126kindling probe init err: bpf_load_program() err=28 event=filler/sys_autofill message=0: (bf) r6 = r1
我看到了关键信息，通常这和编译环境有关，我看到你使用了llvm13,或许是这个版本太高了。你可以使用kindling提供编译镜像进行编译，或者将llvm降到10以下，最好是7.编译文档详见http://www.kindling.space:33215/project-1/doc-13/

**Comment by dxsup** [comment]
@winston-xing 请问这个问题有解决吗，没有解决的话可以提供一下更多信息吗？

**Comment by winston-xing** [comment]
在kindling.cpp的getEvent方法总中加了一个try catch 即对不能识别的事件，进行抛弃。

**Comment by jundizhou** [comment]
Please use package to solve this problem  temporarily. We will solve this problem in next version

[new-build.tar.zip](https://github.com/CloudDectective-Harmonycloud/kindling/files/9565185/new-build.tar.zip)

<img width="974" alt="image" src="https://user-images.githubusercontent.com/92794317/190124713-9e7d7daf-ec43-46d7-b8e5-f772bfe2dff6.png">

**Comment by jundizhou** [comment]
You can refer to the content of faq：1. I only modified the script
http://www.kindling.space:33215/project-1/doc-35/

**Comment by wxingda** [comment]
> 在kindling.cpp的getEvent方法总中加了一个try catch 即对不能识别的事件，进行抛弃。

@winston-xing 我也遇到同样的问题了，请问您是怎么修复的，请指教下，不胜感激！
