### ISSUE TITLE
 mysql协议的sql显示不全

### ISSUE THREAD

**Issue by winston-xing** [KindlingProject/kindling#314]
在otel-collector的输出中， span 的mysql协议的sql显示不全；

![微信图片_20220915142406](https://user-images.githubusercontent.com/37855334/190329804-a705255a-7895-4781-b56d-3902da1c9744.jpg)
![微信图片_20220915142406](https://user-images.githubusercontent.com/37855334/190329811-e2148575-0662-42b5-ad48-8e4e40438332.jpg)

建议将TCP payload参数改成可以配置的。

**Comment by winston-xing** [comment]
![微信图片_20220915142648](https://user-images.githubusercontent.com/37855334/190330191-5cc46f66-4083-4859-ae82-e9fe4d3de812.jpg)
漏掉一个图片

**Comment by jundizhou** [comment]
出于性能考虑，对于每条系统调用，我们默认只从内核截取80bytes的数据，如果你想获取更详细的信息，可以调整该参数，并重新编译，但这会消耗更多的性能
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/92794317/190330778-f62e5235-cf69-4f67-83df-8c9c9734bbfd.png">

**Comment by dxsup** [comment]
我们先把这个字节数调整成200怎么样？毕竟之前测试显示200字节对整体性能的影响并不大，这样可以保证用户看到的数据更有价值。下个版本再把这个值调整成可配置的。
@jundizhou @sanyangji

**Comment by winston-xing** [comment]
可以把字节数调整成200

**Comment by dxsup** [comment]
现在原始事件中的默认字节数大小为1000，而协议中保存的默认字节数大小为200。用户可以通过同时设置环境变量`SNAPLEN`和配置文件中协议保存的字节数来调整最终保存的大小。
