### ISSUE TITLE
No trace data showed using the v0.5.0 agent

### ISSUE THREAD

**Issue by goouoh** [KindlingProject/kindling#389]
环境：Ubuntu 20.04
内核：5.15.0-41-generic
版本：0.5.0
trace不到数据，只能看到trace到了请求
![image](https://user-images.githubusercontent.com/7647086/206372053-f837ab9e-d81c-41f5-bf86-398fcbf109a5.png)
查看kinding-agent日志
![image](https://user-images.githubusercontent.com/7647086/206372322-bde7ca56-dad4-485c-b9dd-feca4a80ec80.png)

**Comment by yaofighting** [comment]
这个可能跟我们前不久修复的一个bug有关，可以尝试编译一下主分支看看是否可以解决。这个是编译安装的指导文档http://www.kindling.space:33215/project-1/doc-13/。这个是相关PR：https://github.com/KindlingProject/kindling/pull/365；https://github.com/KindlingProject/kindling/pull/373

**Comment by goouoh** [comment]
按照[http://www.kindling.space:33215/project-1/doc-13/。](http://www.kindling.space:33215/project-1/doc-13/%E3%80%82)指导文档编译了主分支，问题依然存在

**Comment by dxsup** [comment]
这个问题只在自己编译eBPF时会出现，可能是编译eBPF时的agent-libs版本与编译Kindling时的agent-libs版本不匹配导致的。最新代码解决了这个问题，我们在Ubuntu 20.04(5.15.0-56-generic)验证了可以使用。麻烦使用最新代码重新编译一下eBPF和Kindling，最好先删除agent-libs目录重新下载。

**Comment by dxsup** [comment]
最新代码应该解决了这个问题，如果仍然有问题请重新打开这个issue
