### ISSUE TITLE
完善kindling解析新协议的参考文档

### ISSUE THREAD

**Issue by LambertZhaglog** [KindlingProject/kindling#390]
**Is your feature request related to a problem? Please describe.**
我被公司安排解析两个不同的私有协议，我从Kindling的Blog 和微信公众号上找到了这两个参考资料
- [Kindling如何实现HTTP协议解析](http://jump.harmonycloud.cn:18080/blogs/development/parse-http-protocol/)
- [基于eBPF的开源项目Kindling之Dubbo2 协议开发流程](https://mp.weixin.qq.com/s/XvSpLkfhZMG30Or6eKRsig)

但这两个参考资料对于解析新协议是不完善的，我因此在debug 上花了很长时间。
- 我在解析第一个协议时，发现kindling无法输出自定义标签，调试一周发现，需要在[net_dict.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/consumer/exporter/tools/adapter/net_dict.go) 文件中 entityProtocol 和 topologyProtocol 中加入私有协议的dictionary 。
- 在解析第二个协议时，发现kindling 输出了我期望的request-content 和 Response-content 标签，但这两个标签的值全部为空，又是一周的排查，发现需要在 [label_convert.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/consumer/exporter/tools/adapter/label_converter.go) 文件中的updateProtocolKey 函数中加入一个针对私有协议的case语句。

**Describe the solution you'd like**
在解析这两个协议后，我已经总结出一份完善的 kindling支持解析新协议的步骤，这里希望社区审核和补充，格式参考了[这里](https://mp.weixin.qq.com/s/XvSpLkfhZMG30Or6eKRsig)
1. [protocol.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/network/protocol/protocol.go) 中添加协议名常量，比如 `MAGIC = "magic"`
2. [analyzer/network/protocol](https://github.com/KindlingProject/kindling/tree/main/collector/pkg/component/analyzer/network/protocol) 目录下创建目录（go package），比如报名为magic, 包下至少应有三个文件，magic_parser.go, magic_request.go, magic_response.go，三个文件的内容参照解析http 的package进行填充，核心是magic_request.go要有fastfailMagicRequest 和 parseMagicRequest函数, magic_response.go 要有fastfailMagicResponse 和 parseMagicResponse函数, magic_parser.go 要有NewMagicParser 函数。parseMagicRequest 和parseMagicResponse 函数中大概率要把一些解析结果保存到magic协议特定的标签中，这些特定的标签要在[constlabels/protocols.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/model/constvalues/const.go) 中定义
3. [factory.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/network/protocol/factory/factory.go) import 步骤2 定义的magic package，并且NewParserFactory 函数中添加语句`factory.protocolParsers[protocol.MAGIC] = magic.NewMagicParser()`
4. [label_convert.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/consumer/exporter/tools/adapter/label_converter.go) 文件中的updateProtocolKey 函数中加入case语句`case constvalues.ProtocolMagic:  key.protocol = MAGIC`。语句中的`ProtocolMagic` 要在[constvalues/const.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/model/constvalues/const.go) 中定义, `MAGIC` 要在[net_dict.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/consumer/exporter/tools/adapter/net_dict.go) 的相应常量区定义
5. [net_dict.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/consumer/exporter/tools/adapter/net_dict.go) 文件中 entityProtocol 和 topologyProtocol 中加入magic协议的dictionary，以完成[constlabels/protocols.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/model/constvalues/const.go) 中定义定义magic特定标签到request_content、response_content、status_code 标签的转换
6. [kindling-collector-config.yml](https://github.com/KindlingProject/kindling/blob/main/deploy/agent/kindling-collector-config.yml) 文件中，将magic 协议加入到analyzers.networkanalyzer.protocol_parser 数组中， 并且在analyzers.networkanalyzer.protocol_config 为magic协议指定协议特定端口等
7. [network/protocol/testdata](https://github.com/KindlingProject/kindling/tree/main/collector/pkg/component/analyzer/network/protocol/testdata)路径下添加magic Protocol 的测试用例；[network_analyzer_test.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/network/network_analyzer_test.go) 文件中，实现`TestMagicProtocol` 测试函数
8. 开发magic协议解析过程中，对于新定义的magic协议特定的标签，如果需要把标签值输出为prometheus metric中的label值，在[aggregateprocessor/processor.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/consumer/processor/aggregateprocessor/processor.go)文件中的` newNetRequestLabelSelectors` 函数添加magic协议特定的labelselector，适当增大[maxLabelKeySize](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/aggregator/label_key.go#L53) 的值

**Describe alternatives you've considered**
我虽然总结出这样一份添加步骤，但我并不认为这是能让开发者满意的文档，Kindling 支持新协议的框架设计有很 多值得商榷的地方

1. 首先因为aggregateProcessor在做事件聚合时，会通过LabelSelector挑选DataGroup 中的部分label保留，而现有Dubbo2 解析器遗漏了将DubboErrorCode label 在这里保留，所以Dubbo2 解析后输出的entity metric 的response-content 项始终是0值。这是我从逻辑上分析出的一个bug，暂时没有真实环境验证
2. 从[prometheus metric description](http://120.26.58.66/docs/usage/prometheus-metric/) 的文档中可以看到，kindling 支持不同的网络协议，但不同协议，指标的标签都是相同的。像service metric 中的request-content 和response-content 标签是协议相关的，但标签名是相同的，区分的是标签值的格式、格式的含义。所以我在疑惑，有必要先允许开发者在协议解析阶段自由的 自定义标签，然后再要求开发者小心翼翼地在net-dict.go 文件中将自定义标签转换为metric description 中 定义的标准标签，而且还要留心需要在labelSelector中选择保留自定义标签，这对我来说实在是个疑问！
3. 协议解析阶段定义的协议特定标签的作用范围也只有NetworkAnalyzer、K8sProcessor 组件吧？因为到AggregateProcessor组件，不被LabelSelector的标签都是被丢弃的。协议解析框架强制所有协议使用类似ContentKey 和 StatusCode 标签不是更好？因为这样就不用LabelSelector 和 dictionary了。

**Additional context**

**Comment by dxsup** [comment]
感谢反馈，的确目前在解析协议时要修改的内容较多，对开发者不是很友好，后续我们会通过增加文档和注释、优化字段传递的方式来提高可读性和扩展性。

感谢提供解析步骤，我们一起再整理一下，然后可以提交到Docs中。

**Comment by hocktea214** [comment]
感谢反馈，总结了开发的整体流程如下

* 在协议解析阶段，关注协议如何解析
![image](https://user-images.githubusercontent.com/7486614/206612942-5daa8dfc-ccd9-4976-a65c-c4e040b83ef2.png)

* 在数据保存阶段，关注Key如何映射
![image](https://user-images.githubusercontent.com/7486614/206613002-262411eb-d991-45c1-ab08-9a28e5348f3a.png)

后续会简化流程，自动映射Key，请持续关注

**Comment by LambertZhaglog** [comment]
> 感谢反馈，总结了开发的整体流程如下
> 
> * 在协议解析阶段，关注协议如何解析
>   ![image](https://user-images.githubusercontent.com/7486614/206612942-5daa8dfc-ccd9-4976-a65c-c4e040b83ef2.png)
> * 在数据保存阶段，关注Key如何映射
>   ![image](https://user-images.githubusercontent.com/7486614/206613002-262411eb-d991-45c1-ab08-9a28e5348f3a.png)
> 
> 后续会简化流程，自动映射Key，请持续关注

感谢 @hocktea214 补充 在解析协议时还要有添加测试用例的步骤，我在解析两个协议时就忽视了这一步骤，写测试用例在我看来是验证协议解析正误的很好的方式。我之前只会用Debug Selector 输出到日志来判断新增协议是否正确解析， 测试用例是更省事高效的方式。

**Comment by LambertZhaglog** [comment]
@dxsup @hocktea214 issue description中solution部分补充了步骤7，8，补充了alternative solution， 麻烦再看一下。 当时提issue时太晚了没写完，怕草稿丢失就先提了。你们回复太及时了 :joy:

**Comment by dxsup** [comment]
我也意识到了你提到的问题。当初设计协议的字段时，由于数据输出时要满足多种数据模型（有多种后端），因此希望将协议解析与后续数据输出解耦，然后由不同的开发者完成，当时认为`request-content`, `response-content`, `ContentKey`等属于数据输出的细节，协议解析时不应该关注。Adaptor组件也是基于这样的背景被设计出来的。

但目前已经有多个案例表明，一般开发一个新协议要完全由同一名开发者完成，因此应该将协议解析部分内聚起来，只需要改动这一个地方就可以。将通用字段`request-content`, `response-content`, `ContentKey`等直接放入解析流程是一种方案。

**Comment by dxsup** [comment]
> 3. 协议解析阶段定义的协议特定标签的作用范围也只有NetworkAnalyzer、K8sProcessor 组件吧？因为到AggregateProcessor组件，不被LabelSelector的标签都是被丢弃的。协议解析框架强制所有协议使用类似ContentKey 和 StatusCode 标签不是更好？因为这样就不用LabelSelector 和 dictionary了。

对于metric数据，协议特定标签的作用范围确实如你所说。但是`DataGroup`也会生成span类型的数据，而且存在多个后端需要不同的span数据格式，因此才会引入`net_dictionary`来将协议相关labels映射到其他名称。

最近我们重新梳理了后端的数据格式，部分后端已经不再维护，也许到了该确定唯一一种格式的时候，当我们只有一种格式时，adaptor也就完成了自己的使命，可以废弃了。而如果有人需要其他格式，只要自己实现exporter就好了。 @NeJan2020

**Comment by NeJan2020** [comment]
Adapter目前存在的意义如下：
1. 对象复用：将 DataGroup 输入 otlp-sdk 需要转化成合适的 attribute 列表；而此时如果不复用这个[]attribute对象，则内存开销过大 （simpleAdapter 就是一个不通过复用对象生成attribute的方式）。由于在Span数据中，不同的协议的attribute列表中需要保存的内容也不一致。为了能够重用对象，需要对每种协议提供一个用于重用的attribute列表。类似的，每个指标的列表也在细微处有所差异。最后的结果，就是 由指标+协议才能够确定转换中使用的attribute列表，这是导致adapter复杂的一个原因。
2. 属性名修改： 由于analyzer的输出和exporter后续的组件所需的输出格式可能不一致，exporter目前承担了修改输出格式的任务。比如输出到Prometheus时，如何选择合适的Gauge/Count作为instrument。这个部分目前使用adapter中的dict 和 otlp-exporter 中的instrumentFactory来实现。

我也认可Adapter并不是一个必须的结构，在协议解析这个问题上，约定一些特殊的标签或许比操作一个独立的字典更为方便。

**Comment by LambertZhaglog** [comment]
> 但是DataGroup也会生成span类型的数据，而且存在多个后端需要不同的span数据格式
1. net-dict 没有看到不同的exporter使用不同的span dictionary
2. DataGroup 生成的span类型数据，比如HttpApmTraceId, HttpResponsePayload 因为没被AggregateProcessor的 LabelSelector 保留，到export步骤，这些span 标签已经丢失了的

我同时疑惑为什么要保存span标签，span标签有什么用，希望能提供相关资料，我了解一下。另外这里的span如果是分布式追踪中span的概念，也只有OTELExporter需要span标签吧，我了解OpenTelemetry 有志于做trace和metric 信号的关联，不知道Prometheus也想做这种事情

**Comment by LambertZhaglog** [comment]
> 当初设计协议的字段时，由于数据输出时要满足多种数据模型（有多种后端），因此希望将协议解析与后续数据输出解耦
另外想问，这里的术语"后端" 用来区分 作为OpenTelemetry指标存储的 PrometheusExporter、LoggingExporter、Prometheus Remote Write Exporter这些， 还是用来区分Prometheus 和 OpenTelemetry？

**Comment by dxsup** [comment]
> 2. DataGroup 生成的span类型数据，比如HttpApmTraceId, HttpResponsePayload 因为没被AggregateProcessor的 LabelSelector 保留，到export步骤，这些span 标签已经丢失了的

`networkanalyzer`生成的`DataGroup`的语义是“单次请求详细数据”，这个数据到了`aggregteprocessor`后会走两个分支：
- 一个分支是用`selector`聚合生成统计指标；最终数据名被改为“aggregated_net_request_metric_group”；
- 另一个分支是**采样**这条“单次请求数据”，生成名称为`single_net_request_metric_group`的新数据并向后传递，代码如下：
https://github.com/KindlingProject/kindling/blob/aff27b833289faacdb7d4572f060fc047506f0d1/collector/pkg/component/consumer/processor/aggregateprocessor/processor.go#L116-L123

在上面这个分支中所有labels都会被保留，如果后面使用了otelexporter，则该数据*可以*被作为span类型数据发送出去。

可以发现这里有一个组件设计的问题。`aggregateprocessor`既承担了*聚合*的职责又承担了*采样*的职责，会导致可读性和扩展性变差，这是需要优化的地方。

<br/>

> 1. net-dict 没有看到不同的exporter使用不同的span dictionary

实际上是**相同的exporter**使用**不同的adapter**（由几个dictionary组成）来达到输出不同数据格式的目的。当前对于`single_net_request_metric_group`数据，存在两种输出格式，这两种格式都是由实际需求驱动而开发的：
- 一种是用`opentelemetry-go` SDK输出符合[opentelemetry规范](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto)的span类型，然后发送到opentelemetry-collector作进一步处理。这种格式使用的是`traceToSpanAdapter`;
- 另一种是生成能够存储到prometheus的数据（这是需求，关于“需求是否合理”可以另开一个issue讨论）。由于prometheus无法存储high-cardinality的数据，而我们的`single_net_request_metric_group`又恰巧是这种数据，所以我们要对labels做处理，使用的adapter为`traceToMetricAdapter`

**Comment by dxsup** [comment]
> 我同时疑惑为什么要保存span标签，span标签有什么用，希望能提供相关资料，我了解一下。另外这里的span如果是分布式追踪中span的概念，也只有OTELExporter需要span标签吧，我了解OpenTelemetry 有志于做trace和metric 信号的关联，不知道Prometheus也想做这种事情

我没有完全理解你的问题，你说的“span标签”指的是什么？Kindling存在一个需求是要能够将`single_net_request_metric_group`这种数据以[opentelemetry-proto span](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto)的格式输出给`opentelemetry-collector`。这里的span是opentelemetry的概念，基本等同于分布式追踪中span的概念。

Prometheus并没有想把trace和metric关联，是Kindling希望将`single_net_request_metric_group`数据（类似span的数据）存储到Prometheus中，这样用户不需要引入其他数据库保存span，只需要Prometheus就可以看到单次请求是否有异常。

**Comment by LambertZhaglog** [comment]
> 我没有完全理解你的问题，你说的“span标签”指的是什么？

类似HttpApmTraceId, HttpResponsePayload 这种解析时添加的Attribute。

> Kindling希望将single_net_request_metric_group数据（类似span的数据）存储到Prometheus中，这样用户不需要引入其他数据库保存span，只需要Prometheus就可以看到单次请求是否有异常。

存储的span 在 [prometheus-metric](http://jump.harmonycloud.cn:18080/docs/usage/prometheus-metric/) 有所体现吗？ 没想明白会对应哪个metric的哪个label

**Comment by dxsup** [comment]
这些span标签在用opentelemetry-go sdk输出span时是需要的，保存以后用来查询本次span的详细内容，之前有这些字段的需求。

> 存储的span 在 [prometheus-metric](http://jump.harmonycloud.cn:18080/docs/usage/prometheus-metric/) 有所体现吗？ 没想明白会对应哪个metric的哪个label

有体现，是[Trace As Metric](http://kindling.harmonycloud.cn/docs/usage/prometheus-metric/#trace-as-metric)这一节。其中有提到：
> It is not a good practice to store such data in Prometheus as some labels are high-cardinality, so we picked up some labels from the original ones to generate a new kind of metric, which is called “Trace As Metric”.

可能存在high-cardinality问题的labels都被去掉了，目前labels包括了`topology`指标中的src和dst信息、`entity`指标中的`request_content`和`response_content`、还有由“请求分段耗时“转换的状态码。

**Comment by dxsup** [comment]
我意识到注释、代码和文档中出现了术语不统一的问题，这的确会导致背景和需求无法正确传递，这是一个要解决的问题。

**Comment by dxsup** [comment]
> 另外想问，这里的术语"后端" 用来区分 作为OpenTelemetry指标存储的 PrometheusExporter、LoggingExporter、Prometheus Remote Write Exporter这些， 还是用来区分Prometheus 和 OpenTelemetry？

“后端”指Kindling外部的、要处理Kindling数据的组件，包括Prometheus、opentelemetry-collector或自研其他数据接收器。更准确的说法是，Kindling最初要满足三种不同的数据输出格式，而这三种格式均要使用`otelexporter`这个组件最终对外输出，因此引入了adapter做格式转换。
