### ISSUE TITLE
定义树形多报文结构解析树是必要的吗？

### ISSUE THREAD

**Issue by LambertZhaglog** [KindlingProject/kindling#391]
**Is your feature request related to a problem? Please describe.**
此issue特定针对[protocol_parser.go](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/network/protocol/protocol_parser.go) 中`PkgParser ` 结构体 和 `ParsePkgFn ` 接口提出
[相关资料](https://mp.weixin.qq.com/s/XvSpLkfhZMG30Or6eKRsig)解释
> 对于复杂的多报文协议，如Kafka有不同的API报文，而相同API也有不同的版本报文。将所有报文解析逻辑都 写在一起会使整个类过于臃肿且不易维护。为此引入树形多报文结构用于快速且低耦合地实现开发

我理解，kafka报文协议是两层的格式，需要解析外层拿到api-key 才能确定内层的报文结构。但采用现有设计定 义的解析树的方法，解析完外层协议后，需要逐个尝试内层注册的每个子parser直到解析成功，才终止遍历。定 性分析来说，这种方式做了无用功，性能不高。脱离解析树的概念后，直接根据api-key 选择对应的子parser 不是更直接清晰、高效的方式吗

从软件设计的角度来说，二层协议或多层协议是协议特定的知识，kindling作为支持解析多种网络调用协议的框架，对支持协议的层数做假设或约束的设计是有待商榷的。而且kindling 已经将这种设计表现在接口上，这样造成 新的协议开发者在开发解析器的时候，就要被迫学习”解析树“的概念，要会区分“解析成功”, “解析失败”, “解析未完成”，这是一种 认知负担
**Describe the solution you'd like**
在我看来，“将所有报文解析逻辑都写在一起会使整个类过于臃肿且不易维护”的问题并不存在，不存在多个协议的解析耦合在一起的情况，而且我想，单个协议由单个开发者维护。 这里协议解析的设计越简单越好！ 对于多层报文协议解析的可能带来的问题，我的建议是，把Kafka协议的解析作为一个样板，在相关文档提及，供有类似报文解析需要的开发者做参考

**Comment by hocktea214** [comment]
树型结构 不论是一层还是多层都能有效解耦相关业务逻辑，专注于相关特定子协议的开发
* Mysql为例，根节点负责解析头信息；相关子节点分别解析各自不同报文结构；
* Redis为例，对于array类型包含了其他协议bulk string、int等平级协议，complete返回确保协议树 重入再次解析，减少各种不同场景的if..else判断

当然，如果觉得将所有逻辑写在一个类过于臃肿可以拆分到相关子协议的文件中，类似redis、kafka场景。

此外，对于简单协议简单的API是明了了，但其他稍微嵌套复杂的协议就会在代码细节中出现很多重复代码以及很多其他细节。

**Comment by LambertZhaglog** [comment]
Redis 报文协议比kafka更能说明当前Protocol-parser接口定义的合理性。我目前的观点是，维持当前接口定义或 换用更简单设计并没有绝对优劣，只是设计偏好的问题，重构这部分代码并不必要。但两点补充

1. 我继续坚持这样的判断：当前设计，多层协议的情况，解析完外层逐个尝试内层解析器的方式比直接根据 api-key（kafka)、`message.Data[4]`(mysql), `message.Data[message.Offset]`(redis) 选择内层解析器的方式 要低效
2. 如果选择更简单接口设计，对于Redis存在平级协议的情形，可以用状态机来避免不同场景的if-else 判断，避 免出现重复代码
