### ISSUE TITLE
补充项目设计文档和代码注释

### ISSUE THREAD

**Issue by LambertZhaglog** [KindlingProject/kindling#392]
**Is your feature request related to a problem? Please describe.**
在领导的安排下，我基本完成了公司内部两个私有协议的解析。开始时，用kindling为公司提供可观测性是领导安 排的预研项目，现在协议解析完成，领导想要部署在线上生产集群使用。大领导对此十分慎重，他十分看重线上集 群的稳定性，担心kindling项目的安全性，kindling现在star还较少，暂时还不能获得大领导的信任。我在组内做 对kindling的技术分享时，大领导评价kindling 的前端可视化做得很出色(可视化对可观测尤为重要)，大领导表 示，如果kindling项目真的靠谱，组里最好的方式是把自己的能力集成到kindling上。现在要求，确保项目对公司 来说是安全可控的前提下，才会把kindling投入线上使用，这其中对项目进行代码走读，生成代码阅读报告，是我 必须要完成的任务。

目前，我的精力主要集中在阅读kindling用户态go程序这部分。在代码阅读过程中，注意到项目目前代码中注释较 少，同时缺乏代码全局设计的文档，我倒是在kindling的blog中找到文章[Kindling collector 流水线数据传递流程](http://www.kindling.space:33215/project-1/doc-62/)， 但读起来这篇文章，有错误、不清晰、不完整。
**Describe the solution you'd like**
期望Kindling团队能尽快通过如补充相关设计文档、增加代码注释等来增强项目代码的可读性。万分感激。如果你 们着手做代码可读性的工作，我有以下建议和关注点
1. [buildPipeline](https://github.com/KindlingProject/kindling/blob/main/collector/internal/application/application.go)进行各组件的初始化和连接，如果能在日志中打印输出各组件实际初始化完成后各字段的内容， 会很方便新手的理解，因为做代码阅读时没必要过多精力投入对各组件初始化函数的追踪。当然这还需要注释 中对各组件结构体的各字段有清晰的定义
2. 注意到关键数据有 model.KindlingEvent -> network.messagePairs -> model.DataGroup -> adaptor.AdaptedResult -> model.DataGroup -> prometheus.metric 的核心处理流程，设计文档以此为主线， 解释各组件对关键数据分别做了什么样的改动造成上述数据结构的变化，是一种较好的组织文档的方式。
3. 我在代码阅读过程中，NetworkAnalyzer 和 AggregateProcessor两个组件相对容易理解。如果你们精力有限， 可以优先完善OTELExporter 组件的文档，这个组件的adaptor 和 exporter 代码的阅读难度都很大。比如，我 希望能在文档中解释清楚
   1. adapter 中以metricAdapterBuilder为跳板构造LabelConverter的过程
   2. adapter 中LabelConverter的convert方法和transform 方法的背景知识，就是为什么要做这两种不同的adapt
   3. LabelConverter的 valueLabelsFunc 和 adjustFunctions 字段的解释对外行来说很难理解
   4. kindling对openTelemetry.prometheusExporter 进行深度的定制，并且把部分功能放到 AggregateProcessor实现。这是什么样的定制，定制后的效果什么样的，借助otel很多内部包提供的什么样 的能力？为什么要涉及instrumentFactory，metricController 组件？recordLastValue，RecordBatch分 别做了什么？

**Additional context**
做代码可读性的工作是有些好处的

1. 按大领导的话说，开源这个词是和生态绑定在一起的。我想，Kindling 做好开源，想拥有很好的生态，需要更 多的开发者参与进来，完善的设计文档、清晰的代码注释是降低后来开发者开发门槛，让开发者愿意参与社区的 基础。
2. 设计文档清晰定义和界定了各组件的功能，开发者开发完成后，如果出现bug，设计文档帮助开发者在调试过程 中明确知道应该排查哪个组件，不应该排查哪个组件，从而提升效率。以我的[开发经历](https://github.com/KindlingProject/kindling/issues/390)看，为NetworkAnalyzer 开发一个新的ProtocolParser，发现不能正确输出指标，最终定位问题出在要为AggregateProcessor添加 LabelSelector，为Adaptor添加dictionary，实在是让人沮丧的开发经历。

**Comment by LambertZhaglog** [comment]
找到blog [A Deep Dive Into OpenTelemetry Metrics](https://www.timescale.com/blog/a-deep-dive-into-open-telemetry-metrics/)，由此找到[OpenTelemetry Metric API Specification](https://opentelemetry.io/docs/reference/specification/metrics/api/)，粗略看了下，推想，如果我在阅读kindling exporter部分的源码之前，如果先看了specification，就不至于那么困难，因为明显能感觉到Kindling 源码中在遵循specification中的概念

**Comment by dxsup** [comment]
是的，因为`otelexporter`使用了[opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go)这个SDK。可能我们应该将这部分内容放入组件的注释中，先让开发者了解opentelemetry。

**Comment by litaixun** [comment]
想了解 kindling 的 apm 演示探针的运行原理，但图中两个链接已经失效了，请问还有其他文档渠道吗，目前无法找到源码中下图数据是如何注入到 http header 中的，我们后面想开发私有协议的解析器，而一些类似于火焰图、span 信息等等的数据是来自于 apm 探针的，请问这部分如何处理呢？如何让私有协议也能获得这部分数据呢？我看到目前 kindling 支持的协议中，似乎只有 http 是能够获取 apm 数据的，dubbo 的解析器实现，似乎也没有获取这部分数据，这一块很疑惑，求大佬有空帮帮忙。 @LambertZhaglog 

![Image](https://github.com/user-attachments/assets/0c515d75-96f5-440a-8241-9ff904886802)

![Image](https://github.com/user-attachments/assets/a89ee5f0-aa68-4f69-b90a-7858f6769cc2)
