### ISSUE TITLE
Feature request: Monitor System call exception

### ISSUE THREAD

**Issue by zhy76** [KindlingProject/kindling#408]
**Is your feature request related to a problem? Please describe.**
Feature request: Monitor System call exception

**Describe the solution you'd like**
Monitor System call exception feature will be implemented like:
1. The system can display pid, tid, call type, latency (system call duration) data of the slow system call

2. The system can display the pid, tid, call type and latency of the timeout system call

3. The system can display the pid, tid, return value of the call and error type data of the wrong system call

**Describe alternatives you've considered**

**Additional context**

**Comment by dxsup** [comment]
I think this feature is similar to #366. Is there any reason why you request this feature?
Actually, we have implemented it, but haven't merged it into the main branch due to several reasons.

**Comment by zhy76** [comment]
Thx, Because the current project is based on kindling to implement, there is also a need to monitor both page fault and system calls exception.

**Comment by dxsup** [comment]
Get it. It won't be long before we merge these two features (and #407).

**Comment by zhy76** [comment]
OK,Thanks!

**Comment by dxsup** [comment]
Sorry, we won't be scheduling this feature in the near future since we haven't identified a valuable use case for it yet. We need more information before we can decide whether to continue working on it.
