### ISSUE TITLE
手动构建kindling，启动后报kindling probe init err: SYSDIG_SYSCALL_CODE_ROUTING_TABLE bpf_map_update_elem < 0

### ISSUE THREAD

**Issue by wxingda** [KindlingProject/kindling#414]
**Describe the bug**
出问题的kindling是我手动构建的，基于commit 3cbe7033a00af545ef3483b7d082132c84fd7088，构建完成后，将文件放到了/app目录下
![image](https://user-images.githubusercontent.com/12606514/208901626-a3365c61-cfcb-4943-866e-e603ce5473e5.png)

由于公司的服务器内核是基于4.18.0-193.el8.x86_64定制的，在kindling-falcolib-probe并没有相应的bpf probe，所以我在agent-libs/driver中执行make来构建了自己的probe，然后将/opt/probe.o链接到该probe上面，执行start.sh后，报“kindling probe init err: SYSDIG_SYSCALL_CODE_ROUTING_TABLE bpf_map_update_elem < 0”
![image](https://user-images.githubusercontent.com/12606514/208901768-4194db90-c7c1-4b25-b06f-e8373fe17ae2.png)

**How to reproduce?**
Steps to reproduce the behavior.

**What did you expect to see?**

**What did you see instead?**
A clear and concise description of what you saw instead.

**Screenshots**

**What config did you use?**
Config: (e.g. the yaml config file)

**Logs**
Please attach the logs by running the following command:
```
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-probe
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-collector
```
**Environment (please complete the following information)**
- Kindling agent version
- Kindlinng-falcon-lib version
- Node OS version
- Node Kernel version
- Kubernetes version
- Prometheus version
- Grafana version

**Additional context**
Add any other context about the problem here, like appliction protocol.

**Comment by jundizhou** [comment]
可能是你的定制系统修改了系统调用表。
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/92794317/209047463-5a7e6458-35f9-4d21-a2d1-95589ac4e19e.png">
在这里打点ri日志确认下吧，如果修改了系统调用，就要自己去映射对应了

**Comment by wxingda** [comment]
好的，可以把我拉到交流群里吗，我扫了kindling的二维码，麻烦通过下
