### ISSUE TITLE
falco lib未捕获全部Network syscall 事件？

### ISSUE THREAD

**Issue by LambertZhaglog** [KindlingProject/kindling#436]
**Describe the bug**

因公司自研协议的保密性要求，这是对偶发bug的抽象描述。

使用Magic协议通信的client 和server，只需要建立一个TCP 连接就可以多次通信。参见[这里](https://hpbn.co/http2/#streams-messages-and-frames) 对connection, stream, message 的定义。通信时，每个stream 有一个stream ID(简记为sid)，严格遵守一问一答的方式，即client必须收到前一个stream 的response，才会发出后一个stream的request。sid 置于request和response message的header中，sid 就是stream在connection 上出现的次序，request message中的sid 为正数，response message中的sid 负数。

为了测试kindling解析Magic协议的正确性，设置connection 中所有stream 除sid 外都相同。

解析时，偶发出现，request message 的sid 和 response message的sid 不匹配，即不互为相反数，且都是response sid 的绝对值大于request sid。 tps 小时，response sid 绝对值比request的大1，比如发现requestSid= 1000, responseSid = -1001。 tps 大时，response sid 绝对值可以比request的大十几，比如发现requestSid= 1000, responseSid = -1011。 已验证client 和 server的请求响应正常，即不是业务代码的问题

为分析造成这种异常的原因，在[Network.ConsumeEvent](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/network/network_analyzer.go#L156) 中，设置只处理server捕获的数据包。上述异常会重现。在这里分析收发数据包的sid，发现这样的sid 序列, 20949, -20949, 20950, 20951, 20952, -20952, -20953, 20955, 20956, -20956, -20957, 20958, -20958。 这个序列缺失了-20950, -20951, 20953, 20954, -20954, -20955, 20957。这说明，相应的数据包没有 [Network.ConsumeEvent](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/network/network_analyzer.go#L156) consume。

什么样的偶发?  异常出现和tps 无关，tps 为1, 10, 2000 都会出现。偶发具有“时间局部性”， 很多stream都是正常，突然在一个很小范围内的streams 里出现异常。比例暂认为是200个stream中，会出现一次sid 丢失。

对出现这种异常根因的猜测

1. falco lib判断事件 [Role](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/model/kindling_event.go#L424)的方法不准？
2. falco lib 捕获事件，将事件放入缓冲区，缓冲区溢出，事件被丢弃？缓冲区的问题还可能发生在kindling-probe和kindling-collector 之间
3. falco lib 本身就没有捕获全部的Network syscall

希望社区能评价根因猜测的可能性，指导分析根因

**Comment by dxsup** [comment]
1. 目前还没有出现过Role不准的案例；
2. 这是有可能的，可以看一下标准输出中有关probe获取底层事件的统计指标信息，例如：
```
seen by driver: 879313141
Number of dropped events: 4931018
Number of dropped events caused by full buffer: 4921539
Number of dropped events caused by an invalid condition in the kernel instrumentation: 9479
Number of events skipped due to the tid being in a set of suppressed tids: 680422064
Number of threads currently being suppressed: 568
```
其中`Number of dropped events caused by full buffer`统计的是事件因缓冲区满而被丢弃的数量，这个一般发生在探针没有足够的CPU可用时。根据你的描述：
> 异常出现和tps 无关，tps 为1, 10, 2000 都会出现。偶发具有“时间局部性”， 很多stream都是正常，突然在一个很小范围内的streams 里出现异常。

如果在某个时间窗口内探针没有足够快得处理完数据，就有可能出现这个问题。
3. 确实曾发现了falco libs没有捕获sendmmsg这个系统调用的数据内容，但尚未发现缺失系统调用的情况。且根据你说的“时间局部性”问题，也不太可能是这个问题。

**Comment by dxsup** [comment]
考虑到该协议`严格遵守一问一答的方式`，那么在系统调用层面，应该同样是请求类系统调用和响应类系统调用交替出现。将日志等级调整到debug，输出原始事件，看在丢失sid时，系统调用是否也存在丢失。例如查看序列`20950, 20951, 20952`是否为`request, request, request`，如果是则说明系统调用缺失丢失，再根据统计指标中`Number of dropped events caused by full buffer`是否增加来确定是否是缓冲区溢出。

**Comment by dxsup** [comment]
刚刚在回复 #435 时突然想到，有没有可能事件并没有丢失，而是有一部分sid包含在上一个请求/响应的系统调用中？Magic协议其实也存在同一个系统调用中有多个请求/响应的情况？

**Comment by LambertZhaglog** [comment]
不是这个问题，`而是有一部分sid包含在上一个请求/响应的系统调用中`。 我在日志中输出了KindlingEvent的result value和 data的内容，上一个请求响应的不包含多余的数据
