### ISSUE TITLE
[不成熟的proposal] 面向stream的报文配对与协议解析

### ISSUE THREAD

**Issue by LambertZhaglog** [KindlingProject/kindling#438]
**设计文档的后半段写得很仓促，因为代码实现上我也只写了ContentAnalyzer一个类。还是希望社区能从我模糊的描述中尽量理解我的设想，提供意见，指出问题。后面我进行代码实现时会逐步完善这份文档的。**

# 概念解释

参考[这里](https://hpbn.co/http2/#streams-messages-and-frames)定义connection，stream，message。stream一般由request message 和 response message 组合而成。TCP短连接场景，一个TCP承载一个client 发起的stream。TCP 长连接场景，可能会出现，一个connection 有多个stream，这些stream 可以由client发起，也可以由server发起，多个stream的response message可以逆序，多个stream可以并发进行（类似线程并发的概念，一个stream没有结束，就开始另一个stream）。把当前实现的报文配对方案称为面向connection的报文配对，下面介绍的报文配对方案为面向stream的报文配对。面向connection的报文配对，是面向stream的报文配对的一个特例（超集与子集的关系）。

# 输入描述

面向stream的报文配对要[consume](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/analyzer.go#L21) 如下类型的event

1. 连接建立 – accept，connect 事件
2. 连接断开 – close事件
3. 发报文 – send类 事件
4. 收报文 – recv类 事件

# 处理场景

面向stream的报文配对要能正确处理好下面场景

1. 多个stream并发
2. stream可以由client发起，也可以由server发起
3. 多个stream的response message逆序
4. 单个stream的message分多次接收或发出
5. 多个stream的message可以合并接收或发出
6. kindling启动时，有connection 已经建立，有stream在进行中

# 设计要求

面向stream的报文配对还应该满足下面的要求

1. 抗干扰。不能一个预期外message的出现，导致后续多个stream的message无法配对。预期外的message，比如，多线程共用一个connection，某个线程接收完request message后，因为代码bug 锁住了或崩溃了，不能响应response message。
2. 尽量兼容现有 面向connection的报文配对场景，目标是复用现有的代码
3. 低资源占用，少CPU，低内存开销。要和目前NetworkAnalyzer 开销相当
4. 一定的实时性。比如一个收发包事件已经捕获5s了，就必须要被转换为DataGroup了

# 分阶段的设计目标

此proposal 的最终设计目标是实现ContentAnalyzer去替换NetworkAnalyzer。当前NetworkAnalyzer的功能可以概括为报文配对，协议识别，协议解析。NetworkAnalyzer 不能支持 #435 等场景的原因是，它错误地假设了所有应用层协议都是一问一答的，并在假设下，先报文配对后协议解析。但现实不是这样的，虽然一问一答的假设覆盖了常见的应用层协议，比如NetworkAnalyzer能够很好支持http。现实是，报文配对的方法是应用层协议决定的，是协议的一个特性。

考虑协议识别要依赖协议解析，分两个阶段设计实现ContentAnalyzer

第一阶段：不做协议识别，按照预置端口或默认端口，做协议解析和配对。比如将所有来自80端口的包按照http协议处理，所有53端口的包按DNS协议处理。所有预置端口之外的包，不处理，丢弃。

第二阶段：在第一阶段的基础上，支持处理来自任意端口的包。对于预置端口外的包，分别用ContentAnalyzer支持的协议解析器解析，确定未知端口的包的协议类型

相信达成第一阶段目标，也会让kindling很有用，个人认为，集群中服务大多是按照默认端口提供服务的。

# 第一阶段的设计方案

使用pid+fd唯一的标识一个**connection**，ContentAnalyzer维护connection map，connection map 的key是pid+fd的组合，value是XPair以及和XPair绑定的parser。

把connection 上的收发数据(KindlingEvent)抽象成两个方向的**ByteStream**（字节流），TX ByteStream, RX ByteStream，规定TX ByteStream 来自`IsRequest()==true`的KindlingEvent。一个connection上的TX ByteStream, RX ByteStream 组合成**XPair**。

**parser** 是一个接口，每个应用层协议要实现这个接口， parser的作用是从ByteStream 分割出message，解析message，配对message，输出DataGroup。

ByteStream 要能给出其中每个byte被agent-lib捕获的时间戳、byte在ByteStream上的相对次序、byte的内容（如 果某个byte 因为kindling 或falco lib 不`拿全data`，ByteStream要给出标识）。这是为了，parser分割出 message后，能准确知道message的byte长度、message首尾byte被捕获的时间戳，方便填充DataGroup中的Metric项。

parser在初始化时要和一个XPair绑定（parser中要有一个XPair 的引用）。ContentAnalyzer 定义的parser可以是有状态的，它记忆XPair 上出现过什么样的message。

ByteStream是类似于队列的数据结构，ContentAnalyzer让KindlingEvent入队，parser让bytes出队。

parser提供parseR和parseT方法供ContentAnalyzer 调用，这两个方法被调用的时机可以是，ContentAnalyzer收到send/recv 事件、收到close事件、定时器tick（ContentAnalyzer维护一个定时器）。

## ContentAnalyzer正确处理 #435 的方案

#435 所说的协议，message有固定长度的header，其中有字段标识当前message的长度，可以用来分割message。parser解析这个message，得到stream id，知道message的类型，是request or response。parser 中维护requestMap，key是未完成配对的request message的stream id, value 是 request content。只设计requestMap 而没有response map，是因为所有stream都是先有request message后有response message。解析request message 就加入requestMap。解析response message时，从requestMap 中取相应的request content，完成配对，输出DataGroup

## ContentAnalyzer兼容现有NetworkAnalyzer的方案

RX ByteStream收到KindlingEvent，或收到close事件时，触发parser 分别取ByteStream的全部的数据包，构建[messagePairs](https://github.com/KindlingProject/kindling/blob/main/collector/pkg/component/analyzer/network/message_pair.go#L152)，调用NetworkAnalyzer中的parser解析得到DataGroup

# 第二阶段的设计方案

协议识别的核心在于，复制一个connection上的KindlingEvent，生成多个相同的XPair，但绑定不同类型的parser。这些parser 同时进行解析，最先得到DataGroup的parser，被认为是connection所属的协议类型。

**Comment by LambertZhaglog** [comment]
这个设计实现起来不是那么回事。社区忽略吧。想知道对解决 #435 ，社区有什么计划和想法

**Comment by dxsup** [comment]
其实你的方案整体上是正确的，也是我们之前思考过的如何实现非“一问一答”的通信模型。

由于存在不同种类的通信模型，就要求在关联前先识别到协议是什么通信模型，所以要把“解析协议”前置；由于基于Stream ID的协议允许请求/响应乱序，所以需要将请求以Stream ID作为Key保存到map中，解析到对应的响应时就形成完成的结果。

Pixie就是类似于上述流程完成的协议分析，但对于HTTP/2或GRPC，他们是采用了uprobe实现的，并没有再去解析报文内容（效率低且代码复杂）。观测云没有提供类似的产品。DeepFlow对于HTTP/2也使用了uprobe。

Kindling也正在支持uprobe解析HTTP/2。对于Magic协议，如果不需要获取系统调用中的全部data，则可以按照上述流程实现。

**Comment by dxsup** [comment]
与协议解析模型相关的讨论见#435
