### ISSUE TITLE
Kindling启动或更新导致K8S APIServer OOM崩溃

### ISSUE THREAD

**Issue by LambertZhaglog** [KindlingProject/kindling#459]
**Describe the bug**

在一个拥有30台机器的集群部署和更新Kindling DaemonSet出现了这样的问题：更新DaemonSet配置文件中的容器镜像，然后删除DaemonSet全部的Pod以使镜像更新快速生效。在执行这两步操作后，执行kubectl get pod 查看 Kindling的运行状态，总是被拒绝响应。要等待5到10分钟才能恢复。
> ✗ kubectl -n kindling edit deamonset kindling
✗ kubectl -n kindling get pod -o custom-columns=NAME:.metadata.name  | grep kindling | xargs kubectl -n kindling delete pod >/dev/null
✗ kubectl -n kindling get pods -o wide
E0209 09:21:29.286705 3996882 memcache.go:238] couldn't get current server API group list: Get "https://10.91.173.62:6443/api?timeout=32s": context deadline exceeded - error from a previous attempt: EOF
E0209 09:22:01.287685 3996882 memcache.go:238] couldn't get current server API group list: Get "https://10.91.173.62:6443/api?timeout=32s": context deadline exceeded - error from a previous attempt: EOF
E0209 09:22:51.568619 3996882 memcache.go:238] couldn't get current server API group list: <nil>
Error from server (Forbidden): pods is forbidden: User "xxxxxx" cannot list resource "pods" in API group "" in the namespace "kindling"

查看集群日志发现，删除重建后，Kubernetes API Server 总是因为OOM 崩溃重启。

API Server单实例，且只有16GB内存

集群内pod、service、deployment、ReplicateSet 资源的数量分别是1200、2800、1400、8400

**Comment by dxsup** [comment]
感谢反馈。探针启动时会向API Server发起List请求，获取集群中的Node、ReplicaSet、Service和Pod信息，探针同时启动同时向API Server获取metadata，API Server要返回大量数据，如果内存不足就会OOM。

在你的场景中，ReplicaSet的数量要多得多，这部分有可能可以优化掉。为了获取到pod的workload类型和名字，我们获取了pod的controller信息，但Deployment是两层结构，Deployment是ReplicaSet的controller，ReplicSet是Pod的controller。

曾经我们获取到pod的controller是ReplicaSet后，直接认为workload类型是Deployment，然后截取pod名来获取Deployment的名字；但后来发现有第三方CRD也使用了ReplicaSet作为pod的controller，为了获取到第三方CRD的workload名，采用了先获取ReplicaSet信息，再获取它的controller类型和名字，作为pod的workload类型和名字。

但实际上大多数情况下，ReplicaSet都只有Deployment在使用，我们可以增加一个开关来控制是否获取ReplicaSet的信息，默认情况下不去获取，只有在用户有第三方CRD使用ReplicaSet时才开启。

**Comment by dxsup** [comment]
#492 提供了一个是否获取ReplicaSet元数据的开关`enable_fetch_replicaset`，默认情况下不获取，这样会减少对API server的压力。如果集群中存在第三方CRD使用ReplicaSet作为子controller，则可以开启这个配置。

这个优化应该会显著减小探针对API server的压力，暂时关闭这个issue，如果仍有API server OOM的问题可以再开启。
