### ISSUE TITLE
请问下，现在的版本里，有增加全链路追踪吗？

### ISSUE THREAD

**Issue by xiaodaiit** [KindlingProject/kindling#477]
我看了一下你们的issues,里面有一个traceid span什么的，问一下你们现在增加了调用的全链路追踪吗？

**Comment by dxsup** [comment]
Kindling没有tracing全链路追踪的能力。我们提到的traceid和span是用来实现[Trace Profiling](http://kindling.harmonycloud.cn/docs/overview-and-concepts/trace-profiling/)功能，可以在官网找到这个功能的Demo，实际体验一下。
