### ISSUE TITLE
grafana topology crash frequently 

### ISSUE THREAD

**Issue by yanhongchang** [KindlingProject/kindling#482]
**Describe the bug**
Found the grafana topology always crash when used normally，especially change the time range. 

**How to reproduce?**
it is easier to reproduce when the cluster has a large number of resources， for example，3K+ pods、10k+ rs、3k+ deployment  in my k8s cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/10663031/224650861-d7170a0c-7cee-48e7-8e6e-c3da3e33e210.png)

**Environment (please complete the following information)**
- Kindling agent version
- 0.7.1

- Kindlinng-falcon-lib version

- Node OS version
- centos8

- Node Kernel version
- 5.10

- Kubernetes version
- 1.20

- Prometheus version
- 0.37.0

- Grafana version
- 0.7.1

**Comment by dxsup** [comment]
Thanks for reporting, but we can't reproduce it now. We'll have a retry later. If any others could reproduce this issue, please leave a comment and let me know.

**Comment by wenhuwang** [comment]
and my grafana topology panel never loads successfully data, after a while it crashes

**Comment by dxsup** [comment]
> and my grafana topology panel never loads successfully data, after a while it crashes

Does it load successfully in the other dashboard?

**Comment by wenhuwang** [comment]
> > and my grafana topology panel never loads successfully data, after a while it crashes
> 
> Does it load successfully in the other dashboard?

Other panels load data successfully, and another three-node clusters topology panel is also load data successfully.

**Comment by wenhuwang** [comment]
The promQL expression used by topology panelpanel also has data in prometheus. I guess there should be a performance bottleneck in the data processing of this panel.

**Comment by dxsup** [comment]
We had ever filtered data in the `namespace` level to reduce the data returned, but this caused an issue of missing some workloads, so we didn't adopt it. Recently, we managed to find a new way to solve this problem by introducing a new metric, but it will take some time to complete. We hope to finish it within the next two weeks.

**Comment by wenhuwang** [comment]
> We had ever filtered data in the `namespace` level to reduce the data returned, but this caused an issue of missing some workloads, so we didn't adopt it. Recently, we managed to find a new way to solve this problem by introducing a new metric, but it will take some time to complete. We hope to finish it within the next two weeks.

Is there any documentation for the new way?

**Comment by dxsup** [comment]
We will address the proposal here once we finish it.

**Comment by dxsup** [comment]
> We had ever filtered data in the `namespace` level to reduce the data returned, but this caused an issue of missing some workloads, so we didn't adopt it. Recently, we managed to find a new way to solve this problem by introducing a new metric, but it will take some time to complete. We hope to finish it within the next two weeks.

The reason why this approach doesn't work is due to the limitation of Grafana's variable feature, which does not support writing queries with OR conditions. As a result, when filtering the namespace and querying the corresponding metrics, it is only possible to choose either the source workload (src_workload) or the destination workload (dst_workload). This limitation leads to missing data in the workload list.

To resolve this issue, a new metric data needs to be provided. This new metric data should allow retrieving all workloads under a specific namespace based on the namespace itself. By introducing this new metric data, it will be possible to overcome the limitations of the variable feature and obtain a comprehensive list of workloads for a given namespace.

We are still working on this.

**Comment by dxsup** [comment]
We have implemented the proposed changes in PR #530 #531, and this enhancement is included in the v0.8.0 release. The fix should address the crash issue in the majority of cases. If you encounter any further crashes, please feel free to reopen the issue and provide additional details.
