### ISSUE TITLE
kindling始终drop event by full buffer

### ISSUE THREAD

**Issue by LambertZhaglog** [KindlingProject/kindling#491]
**Describe the bug**

Kindling自启动后，日志中打印的"Number of dropped events caused by full buffer"数值一直在增加，偶尔突然丢失很多事件，但CPU 配额4 core，实际使用最多1.5core
**How to reproduce?**

自启动后，Kindling的CPU使用率随时间变化如图
![image](https://user-images.githubusercontent.com/28868217/226930909-343c6980-a6fc-476e-9e69-023633afc065.png)

event seen by driver 个数随时间变化如图
![image](https://user-images.githubusercontent.com/28868217/226931298-cf912500-1957-406b-99cf-5f1b386c2f0a.png)

Number of dropped events caused by full buffer 随时间变化如图
![image](https://user-images.githubusercontent.com/28868217/226931531-ae4b4158-ced1-4bfc-9e67-116149ac44d1.png)

event seen by driver 和 drop by full buffer的详细数据 如表 
[event.log](https://github.com/KindlingProject/kindling/files/11040958/event.log)

**What did you expect to see?**

CPU 占用不满，Number of dropped events caused by full buffer 应始终为0

**Environment (please complete the following information)**
- Kindling agent version 34c8f8d58eaa9844952bb8c2f771674131c5f63d
- Kindlinng-falcon-lib version 9004898d4ea7ba9baf7860c0147a540a0774b45c
- Node OS version Debian GNU/Linux 9 (stretch)
- Node Kernel version Debian GNU/Linux 9 (stretch)   4.19.0-0.bpo.8-amd64
- Kubernetes version v1.18.3

**Comment by jundizhou** [comment]
请提供一下对应的日志 对每个事件的统计

**Comment by LambertZhaglog** [comment]
@jundizhou 因pod重启，原始日志丢失。
这是另一台机器的[日志](https://github.com/KindlingProject/kindling/files/11075385/dl-48-head.log) ，日志中同样"Number of dropped events caused by full buffer"数值一直在增加，但CPU 配额4 core，实际使用最多0.7core
![image](https://user-images.githubusercontent.com/28868217/227860977-c30bb563-39a6-4aec-820b-45b531959947.png)

Kindling agent version https://github.com/KindlingProject/kindling/commit/34c8f8d58eaa9844952bb8c2f771674131c5f63d
Kindlinng-falcon-lib version 9004898d4ea7ba9baf7860c0147a540a0774b45c
Node OS version Debian GNU/Linux 9 (stretch)
Node Kernel version Debian GNU/Linux 9 (stretch) 4.19.0-0.bpo.19-amd64
Kubernetes version v1.18.3

**Comment by LambertZhaglog** [comment]
BUF_SIZE_PAGES 什么取值范围？ 我把它设置为32768，kindling-agent启动失败，“kindling probe init err: failure populating program array2023/03/28 03:28:18 Failed to run application: failed to start application: fail to init probe ”。

> 可能是调整了snap_len为10000引起的

我把这个snap_len 调整回1000，在一台机器上，观察到9h 共event drop by full 个数为9000，一台机器9h 共event drop by full 个数为6000。相同的镜像，另外一台机器，9h event drop by full 个数为160000

**Comment by jundizhou** [comment]
> BUF_SIZE_PAGES 什么取值范围？ 我把它设置为32768，kindling-agent启动失败，“kindling probe init err: failure populating program array2023/03/28 03:28:18 Failed to run application: failed to start application: fail to init probe ”。
> 
> > 可能是调整了snap_len为10000引起的
> 
> 我把这个snap_len 调整回1000，在一台机器上，观察到9h 共event drop by full 个数为9000，一台机器9h 共event drop by full 个数为6000。相同的镜像，另外一台机器，9h event drop by full 个数为160000

理论上可以设置81920个字节，但是可能引发其他未知bug，方便的话，提供下设置32768的日志。
event drop by full数量增长不快的情况，极大可能丢失的是futex等事件， 只有很小概率影响最后分析结果准确性，如果你在意这个，可以按照我上面说的调大map来缓解。

**Comment by LambertZhaglog** [comment]
[32768的日志](https://github.com/KindlingProject/kindling/files/11085118/dl362.log)
