### ISSUE TITLE
有没有企业版本的试用方式？

### ISSUE THREAD

**Issue by llhhbc** [KindlingProject/kindling#522]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dxsup** [comment]
可以先加一下kindling的官方微信群

**Comment by llhhbc** [comment]
这个已经加过了，发信息什么的，没有回复

**Comment by Kindling-project** [comment]
官方微信已经拉群，问题解决了吗？

**Comment by llhhbc** [comment]
已经解决了，谢谢。
