### ISSUE TITLE
linux内核6.2.1下重新编译agent失败

### ISSUE THREAD

**Issue by zljun2010** [KindlingProject/kindling#545]
报错信息如下：

Compile probe for 6.2.1-1.el7.elrepo.x86_64
make -C /lib/modules/6.2.1-1.el7.elrepo.x86_64/build M=/source/driver modules
make[1]: Entering directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'
  CC [M]  /source/driver/main.o
/source/driver/main.c: In function 'sysdig_init':
/source/driver/main.c:2816:23: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
 2816 |  g_ppm_class->devnode = ppm_devnode;
      |                       ^
cc1: some warnings being treated as errors
make[3]: *** [/source/driver/main.o] Error 1
make[2]: *** [/source/driver] Error 2
make[1]: *** [__sub-make] Error 2
make[1]: Leaving directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'
make: *** [all] Error 2
mv: cannot stat 'kindling-falcolib-probe.ko': No such file or directory
make -C /lib/modules/6.2.1-1.el7.elrepo.x86_64/build M=/source/driver clean
make[1]: Entering directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'
make[1]: Leaving directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'
6.2.1-1.el7.elrepo.x86_64
make -C /lib/modules/6.2.1-1.el7.elrepo.x86_64/build M=$PWD
make[1]: Entering directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'
clang -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h \
         -D__KERNEL__    \
         \
         \
        -DCPU_ANALYSIS \
        -D__KERNEL__ \
        -D__BPF_TRACING__ \
        -Wno-gnu-variable-sized-type-not-at-end \
        -Wno-address-of-packed-member \
        -fno-jump-tables \
        -fno-stack-protector \
        -Wno-tautological-compare \
        -Wno-incompatible-pointer-types-discards-qualifiers \
        -O2 -g -emit-llvm -c /source/driver/bpf/probe.c -o /source/driver/bpf/probe.ll
In file included from /source/driver/bpf/probe.c:26:
/source/driver/bpf/fillers.h:841:49: error: member reference base type 'struct percpu_counter [4]' is not a structure or union
        bpf_probe_read(&val, sizeof(val), &mm->rss_stat.count[member]);
                                           ~~~~~~~~~~~~^~~~~~
1 error generated.
make[3]: *** [/source/driver/bpf/probe.o] Error 1
make[2]: *** [/source/driver/bpf] Error 2
make[1]: *** [__sub-make] Error 2
make[1]: Leaving directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'
make: *** [all] Error 2
mv: cannot stat 'probe.o': No such file or directory
make -C /lib/modules/6.2.1-1.el7.elrepo.x86_64/build M=$PWD clean
make[1]: Entering directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'
make[1]: Leaving directory `/host/usr/src/kernels/6.2.1-1.el7.elrepo.x86_64'

**Comment by dxsup** [comment]
目前还没有适配6.x的内核版本，后续会排期支持。

**Comment by jundizhou** [comment]
https://github.com/KindlingProject/agent-libs/pull/39 我已经在该pr解决此报错
