### ISSUE TITLE
DNS域名解析异常指标收集不全

### ISSUE THREAD

**Issue by yanhongchang** [KindlingProject/kindling#547]
**Describe the bug**

通过日志可以看到域名解析有很大的延迟，但是在kindling_trace_request_duration_nanoseconds指标中却看不到对应的异常记录数据，怀疑agent在收集指标时有丢失。

![image](https://github.com/KindlingProject/kindling/assets/10663031/eee8f0dd-0622-4b11-8f46-79c33441352b)
通过以上日志可以看到有很多解析超时记录

但是通过kindling的grafana看，却没有对应的异常记录。

![image](https://github.com/KindlingProject/kindling/assets/10663031/e711e35d-b143-4ea1-a0f9-defe27dffa78)

而且查看kindling-agent日志，对应时间点也没有发现有指标丢失的记录。

![image](https://github.com/KindlingProject/kindling/assets/10663031/d6b840dd-be43-4481-9312-071925a26d87)

- Kindling agent version 
    0.7.2 

- Node Kernel version  
     5.10.23-4.al8.x86_64

- Kubernetes version
   1.20.4

**Comment by Kindling-project** [comment]
请问两者看到的域名是一致的吗？

**Comment by yanhongchang** [comment]
> 请问两者看到的域名是一致的吗？

日志在2023-0713 21:31:35 这一两秒出现11个解析异常的请求，在 grafana看板 21:30 -- 21:40 这个时间范围内只有几个latency 为0的 同域名的记录，数量也对不上
 
![image](https://github.com/KindlingProject/kindling/assets/10663031/b2120e1a-6f52-478d-9401-2363b68184bc)

**Comment by Kindling-project** [comment]
其实我们想了解的是，如何判断当时出现了域名解析延时很大，第一张图的域名解析是日志打出来的吗？我们的工作原理是解析DNS的报文，也得明确下DNS服务器是公网的，还是k8s的coreDNS之类的。

**Comment by yanhongchang** [comment]
> 其实我们想了解的是，如何判断当时出现了域名解析延时很大，第一张图的域名解析是日志打出来的吗？我们的工作原理是解析DNS的报文，也得明确下DNS服务器是公网的，还是k8s的coreDNS之类的。

第一张图就是业务打印出来的域名解析异常的日志，dns服务是集群内部的dns提供的解析服务。

**Comment by hocktea214** [comment]
探针版本是否已更新到 [0.8.0](https://github.com/KindlingProject/kindling/releases)，Fix了Tcp协议下的DNS域名解析？

**Comment by yanhongchang** [comment]
> 探针版本是否已更新到 [0.8.0](https://github.com/KindlingProject/kindling/releases)，Fix了Tcp协议下的DNS域名解析？

这个0.8.0 fix的问题还是我反馈的，不是解决dns解析domain缺失的问题？跟我这里提到的解析异常记录不全不太一样吧？
