### ISSUE TITLE
有关该工具监控对象的一些问题

### ISSUE THREAD

**Issue by zhangzihengya** [KindlingProject/kindling#609]
你好，我看了该项目的reademe后，有几个问题想请教下：
1. 这个开源工具只能监控java语言的应用程序还是所有语言的应用程序？
2. 该工具可以监控应用程序的用户态行为吗？像用户态互斥锁的加锁解锁操作、fork、vfork等

**Comment by Kindling-project** [comment]
Kindling两部分功能，一部分是网络拓扑指标，这部分是与语言无关的。另外一部分trace-profiling和语言相关，目前只支持java。Trace-profiling能够通过系统调用futex发现应用的锁行为

**Comment by zhangzihengya** [comment]
> Kindling两部分功能，一部分是网络拓扑指标，这部分是与语言无关的。另外一部分trace-profiling和语言相关，目前只支持java。Trace-profiling能够通过系统调用futex发现应用的锁行为

好的非常感谢，一个非常不错的项目
