### ISSUE TITLE
你好，请问是否支持监控传统安装在Linux服务器，不是k8s的应用

### ISSUE THREAD

**Issue by cfy3133** [KindlingProject/kindling#610]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dxsup** [comment]
能够监控，但由于缺失k8s中的关联信息，只能看到IP地址。
另外要监控传统Linux服务器，建议使用docker启动，具体启动方式要参考`deploy`目录下的`kindling-agent-deploy.yml`。

**Comment by cfy3133** [comment]
好的，谢谢作者耐心回答
