### ISSUE TITLE
agent上报非本机节点pod冗余信息，导致指标kindling_k8s_workload_info量飙升

### ISSUE THREAD

**Issue by yanhongchang** [KindlingProject/kindling#638]
这个问题应该是在0.8.1版本优化过了（https://github.com/KindlingProject/kindling/pull/554）
但是现在看v0.9.1版本又出现了，可能是后续提交的代码对这个优化造成了影响。

**Comment by dxsup** [comment]
使用的是metadata-provider还是agent直连api-server？

**Comment by yanhongchang** [comment]
> 使用的是metadata-provider还是agent直连api-server？

metadata-provider 模式

**Comment by dxsup** [comment]
metadata-provider 模式确实有这个问题，我们修复一下

**Comment by yanhongchang** [comment]
> metadata-provider 模式确实有这个问题，我们修复一下

OKOK

**Comment by dxsup** [comment]
Closed via #639
